version: "3.8"

services:
  frontend:
    container_name: vite-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    container_name: spring-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
      - ~/.m2:/root/m2 # Cache Maven Deps
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/military-assets
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: military-assets
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
