services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: military-assets
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
